from __future__ import annotations

from fs_schema.schema import (
    CountRule,
    EntryKind,
    ForbidRule,
    ImpliesRule,
    RequireRule,
    Rule,
    Schema,
)


def compile_to_bash(schema: Schema) -> str:
    sections = [_render_header(schema), _render_helpers(schema)]
    for index, rule in enumerate(schema.rules):
        sections.append(_render_rule(rule, index=index))
    sections.append(_FOOTER)
    return "\n".join(sections)


def _bash_string_literal(value: str) -> str:
    escaped = value.replace("'", "'\\''")
    return f"'{escaped}'"


def _render_header(schema: Schema) -> str:
    case_sensitive = "true" if schema.options.case_sensitive else "false"
    follow_symlinks = "true" if schema.options.follow_symlinks else "false"
    return f"""\
#!/usr/bin/env bash
# This script was generated by `fs-schema compile`.
# Validates the file system tree at the given root directory against the
# original FS Schema. Exits with status 0 on success and 1 on validation
# failure. The root directory may be given as the first argument and
# defaults to the current directory.
set -u

fs_schema__case_sensitive={case_sensitive}
fs_schema__follow_symlinks={follow_symlinks}

if [ "$#" -ge 1 ]; then
    fs_schema__root="$1"
else
    fs_schema__root="."
fi

if [ ! -d "$fs_schema__root" ]; then
    printf 'fs-schema: not a directory: %s\\n' "$fs_schema__root" >&2
    exit 2
fi

fs_schema__exit_code=0
"""


_HELPERS = r"""
fs_schema__emit() {
    printf '[%s] %s\n' "$1" "$2" >&2
    fs_schema__exit_code=1
}

fs_schema__kind_of() {
    if [ -L "$1" ] && [ "$fs_schema__follow_symlinks" != true ]; then
        printf 'symlink'
        return
    fi
    if [ -d "$1" ]; then
        printf 'directory'
    elif [ -f "$1" ]; then
        printf 'file'
    elif [ -L "$1" ]; then
        printf 'symlink'
    fi
}

fs_schema__list_entries() {
    (
        cd "$fs_schema__root" || return 1
        find . -mindepth 1 -print 2>/dev/null | LC_ALL=C sort
    ) | while IFS= read -r fs_schema__entry; do
        fs_schema__path="${fs_schema__entry#./}"
        fs_schema__kind=$(fs_schema__kind_of "$fs_schema__root/$fs_schema__path")
        if [ -z "$fs_schema__kind" ]; then
            continue
        fi
        printf '%s\t%s\n' "$fs_schema__path" "$fs_schema__kind"
    done
}
"""


_REGEX_MATCH = r"""
fs_schema__regex_match() {
    local pattern="$1"
    local value="$2"
    if [ "$fs_schema__case_sensitive" = true ]; then
        [[ "$value" =~ ^${pattern}$ ]]
    else
        shopt -s nocasematch
        [[ "$value" =~ ^${pattern}$ ]]
        local rc=$?
        shopt -u nocasematch
        return "$rc"
    fi
}
"""


def _render_helpers(schema: Schema) -> str:
    parts = [_HELPERS]
    if _needs_regex_helpers(schema):
        parts.append(_REGEX_MATCH)
    return "".join(parts)


def _needs_regex_helpers(schema: Schema) -> bool:
    return any(_rule_uses_enumeration(rule) for rule in schema.rules) or (
        not schema.options.case_sensitive
    )


def _rule_uses_enumeration(rule: Rule) -> bool:
    if isinstance(rule, RequireRule | ForbidRule):
        return rule.path_regex is not None
    return isinstance(rule, CountRule)


def _render_rule(rule: Rule, *, index: int) -> str:
    header = f"# rule[{index}]: id={rule.id}, type={rule.type.value}\n"
    if isinstance(rule, RequireRule):
        body = _render_require(rule)
    elif isinstance(rule, ForbidRule):
        body = _render_forbid(rule)
    elif isinstance(rule, ImpliesRule):
        body = _render_implies(rule)
    else:
        body = _render_count(rule)
    return header + body


def _render_require(rule: RequireRule) -> str:
    if rule.path is not None:
        return _render_require_path(rule)
    return _render_require_path_regex(rule)


def _render_require_path(rule: RequireRule) -> str:
    assert rule.path is not None
    path_lit = _bash_string_literal(rule.path)
    expected = _bash_string_literal(rule.kind.value)
    missing = _bash_string_literal(f"{rule.path} does not exist")
    mismatch = _bash_string_literal(f"{rule.path} has an unexpected kind")
    return f"""{{
    fs_schema__path={path_lit}
    fs_schema__actual=$(fs_schema__kind_of "$fs_schema__root/$fs_schema__path")
    if [ -z "$fs_schema__actual" ]; then
        fs_schema__emit missing {missing}
    elif [ "$fs_schema__actual" != {expected} ]; then
        fs_schema__emit kind_mismatch {mismatch}
    fi
}}
"""


def _render_require_path_regex(rule: RequireRule) -> str:
    assert rule.path_regex is not None
    selector = f"path_regex={rule.path_regex}"
    pattern_lit = _bash_string_literal(rule.path_regex)
    expected = _bash_string_literal(rule.kind.value)
    missing = _bash_string_literal(f"{selector} does not exist")
    return f"""{{
    fs_schema__matched_paths=()
    fs_schema__matched_kinds=()
    while IFS=$'\\t' read -r fs_schema__p fs_schema__k; do
        if fs_schema__regex_match {pattern_lit} "$fs_schema__p"; then
            fs_schema__matched_paths+=("$fs_schema__p")
            fs_schema__matched_kinds+=("$fs_schema__k")
        fi
    done < <(fs_schema__list_entries)
    if [ "${{#fs_schema__matched_paths[@]}}" -eq 0 ]; then
        fs_schema__emit missing {missing}
    else
        fs_schema__has_correct=0
        for fs_schema__k in "${{fs_schema__matched_kinds[@]}}"; do
            if [ "$fs_schema__k" = {expected} ]; then
                fs_schema__has_correct=1
                break
            fi
        done
        if [ "$fs_schema__has_correct" -eq 0 ]; then
            fs_schema__i=0
            while [ "$fs_schema__i" -lt "${{#fs_schema__matched_paths[@]}}" ]; do
                fs_schema__emit kind_mismatch \
                    "${{fs_schema__matched_paths[$fs_schema__i]}} has an unexpected kind"
                fs_schema__i=$((fs_schema__i + 1))
            done
        fi
    fi
}}
"""


def _render_forbid(rule: ForbidRule) -> str:
    if rule.path is not None:
        return _render_forbid_path(rule)
    return _render_forbid_path_regex(rule)


def _render_forbid_path(rule: ForbidRule) -> str:
    assert rule.path is not None
    path_lit = _bash_string_literal(rule.path)
    expected = _bash_string_literal(rule.kind.value)
    forbidden = _bash_string_literal(f"{rule.path} must not exist")
    return f"""{{
    fs_schema__path={path_lit}
    fs_schema__actual=$(fs_schema__kind_of "$fs_schema__root/$fs_schema__path")
    if [ "$fs_schema__actual" = {expected} ]; then
        fs_schema__emit forbidden {forbidden}
    fi
}}
"""


def _render_forbid_path_regex(rule: ForbidRule) -> str:
    assert rule.path_regex is not None
    pattern_lit = _bash_string_literal(rule.path_regex)
    expected = _bash_string_literal(rule.kind.value)
    return f"""{{
    while IFS=$'\\t' read -r fs_schema__p fs_schema__k; do
        if fs_schema__regex_match {pattern_lit} "$fs_schema__p" \
            && [ "$fs_schema__k" = {expected} ]; then
            fs_schema__emit forbidden "$fs_schema__p must not exist"
        fi
    done < <(fs_schema__list_entries)
}}
"""


def _render_implies(rule: ImpliesRule) -> str:
    if_path = _bash_string_literal(rule.if_selector.path)
    then_path = _bash_string_literal(rule.then_selector.path)
    message = _bash_string_literal(
        f"{rule.then_selector.path} does not exist "
        f"but is required because {rule.if_selector.path} exists",
    )
    return f"""{{
    fs_schema__if_kind=$(fs_schema__kind_of "$fs_schema__root/"{if_path})
    fs_schema__then_kind=$(fs_schema__kind_of "$fs_schema__root/"{then_path})
    if [ -n "$fs_schema__if_kind" ] && [ -z "$fs_schema__then_kind" ]; then
        fs_schema__emit implied_missing {message}
    fi
}}
"""


def _render_count(rule: CountRule) -> str:
    selector_text = f"path_regex={rule.select.path_regex}"
    if rule.select.kind is not None:
        selector_text = f"{selector_text}, kind={rule.select.kind.value}"
    pattern_lit = _bash_string_literal(rule.select.path_regex)
    kind_filter = _render_count_kind_filter(rule.select.kind)
    bound_check = _render_count_bound_check(rule, selector_text)
    return f"""{{
    fs_schema__count=0
    while IFS=$'\\t' read -r fs_schema__p fs_schema__k; do
        if fs_schema__regex_match {pattern_lit} "$fs_schema__p"{kind_filter}; then
            fs_schema__count=$((fs_schema__count + 1))
        fi
    done < <(fs_schema__list_entries)
{bound_check}
}}
"""


def _render_count_kind_filter(kind: EntryKind | None) -> str:
    if kind is None:
        return ""
    return f' && [ "$fs_schema__k" = {_bash_string_literal(kind.value)} ]'


def _render_count_bound_check(rule: CountRule, selector_text: str) -> str:
    lines: list[str] = []
    selector_lit = _bash_string_literal(selector_text)
    if rule.minimum is not None:
        format_lit = _bash_string_literal(
            f"%s matched %d entries, which is less than minimum={rule.minimum}",
        )
        lines.append(
            f"""    if [ "$fs_schema__count" -lt {rule.minimum} ]; then
        fs_schema__msg=$(printf {format_lit} {selector_lit} "$fs_schema__count")
        fs_schema__emit count_out_of_range "$fs_schema__msg"
    fi""",
        )
    if rule.maximum is not None:
        format_lit = _bash_string_literal(
            f"%s matched %d entries, which is greater than maximum={rule.maximum}",
        )
        lines.append(
            f"""    if [ "$fs_schema__count" -gt {rule.maximum} ]; then
        fs_schema__msg=$(printf {format_lit} {selector_lit} "$fs_schema__count")
        fs_schema__emit count_out_of_range "$fs_schema__msg"
    fi""",
        )
    return "\n".join(lines)


_FOOTER = """\
exit "$fs_schema__exit_code"
"""
